2.4 migration guide
meteor/guide pull request #1081
Opened 2021-08-16 19:36 UTC by StorytellerCZ

In preparations for 2.4 release here is a quick migration guide as they were done until v1.7. I will look into creating ones for the missing versions as well to have guide complete in the future (maybe in this PR if I can manage it before it gets merged, but they will have to be backported to the old versions).

2021-08-16 21:27 UTC, filipenevola requested changes
Why do we need to have this here?

Before Meteor 1.8 we didn't have migration steps as a section in the History.md but now we do so we should centralize this there.

2021-08-17 10:42 UTC, StorytellerCZ commented
@filipenevola ease of access, especially for users that are upgrading from older releases (easier to have this extract) or new users who are still unfamiliar with the changelog or visiting the repository to get news.

2021-08-18 13:50 UTC, filipenevola commented
> @filipenevola ease of access, especially for users that are upgrading from older releases (easier to have this extract) or new users who are still unfamiliar with the changelog or visiting the repository to get news.
> 
> But it is a worthy discussion if this is something that we should have or remove.

The changelog is in the [docs](https://docs.meteor.com/changelog.html), it's enough. I don't see how spreading the content here would help.

Ideally we should even remove History.md and start using Github Releases as almost every project does.

2021-08-19 14:37 UTC, StorytellerCZ commented
We could do the releases. I can start on that if you want and then I can remove migrations from here entirely.

2021-08-20 01:33 UTC, filipenevola commented
We can close this cycle like this and decide what do to next for Meteor 2.5.

2021-08-20 14:08 UTC, StorytellerCZ commented
@filipenevola I'm not sure I understand, do you want to merge this or leave this for 2.5?

2021-08-20 14:18 UTC, filipenevola commented
> @filipenevola I'm not sure I understand, do you want to merge this or leave this for 2.5?

Now that this work in already done you can merge it and we discuss how we want to move forward starting from 2.5

2021-09-15 11:05 UTC, merged